// Fictional coastal departures for the local client preview only.
const coastImages={
 'arraial':'https://www.turismo.rj.gov.br/wp-content/uploads/2020/03/Vista-Aérea-Ilha-do-Farol-Prainhas-e-Praia-Brava-scaled.jpg',
 'ilha-grande':'https://angra.rj.gov.br/pmar/assets/img/arquivos/68e0273893a2d.jpg',
 'ubatuba':'https://turismo.ubatuba.sp.gov.br/wp-content/uploads/sites/29/2014/11/DSC04657.jpg',
 'ilhabela':'https://www.ilhabela.sp.gov.br/fotos/3d409d95371a39f7572055c9e3ce49f0.jpg',
 'guarapari':'https://turismoespiritosanto.es.gov.br/Media/DescubraOEspiritoSanto/Fotos/marcelomoryan_enseadaazul_guarapari_es_40909065661_o.jpg'
};
const coastVideo='https://cdn.coverr.co/videos/coverr-raglan-beach-in-new-zealand-958/1080p.mp4';
originOptions.splice(0,originOptions.length,['all','Todas as cidades'],['rio','Rio de Janeiro · RJ'],['niteroi','Niterói · RJ'],['sp','São Paulo · SP'],['sjc','São José dos Campos · SP'],['vitoria','Vitória · ES'],['vila-velha','Vila Velha · ES']);
const coastBases=[
 {id:'arraial',name:'Arraial do Cabo',category:'Litoral do RJ',state:'RJ',origins:['rio','niteroi'],boarding:['Rio de Janeiro · Centro · 05h','Niterói · Centro · 05h40'],subtitle:'Azul por todos os lados e um dia com os pés na areia.',description:'Uma excursão demonstrativa para conhecer o litoral de Arraial do Cabo, na Região dos Lagos. Tempo livre para aproveitar a orla e as paisagens. Passeios de barco e acessos especiais não estão incluídos nesta oferta fictícia.'},
 {id:'ilha-grande',name:'Ilha Grande',category:'Ilhas & natureza',state:'RJ',origins:['rio'],boarding:['Rio de Janeiro · Centro · 05h'],subtitle:'Mar, Mata Atlântica e o ritmo tranquilo de uma ilha.',description:'Excursão ilustrativa para a região de Ilha Grande, em Angra dos Reis. Este exemplo considera transporte terrestre e travessia até a Vila do Abraão. Passeios adicionais, trilhas guiadas e acesso a outras praias devem ser combinados à parte. Operação e travessia dependem de confirmação do organizador.'},
 {id:'ubatuba',name:'Ubatuba',category:'Litoral de SP',state:'SP',origins:['sp','sjc'],boarding:['São Paulo · Tietê · 04h30','São José dos Campos · Centro · 06h'],subtitle:'Praias cercadas de verde e um respiro no litoral norte.',description:'Saída demonstrativa para Ubatuba, no litoral norte de São Paulo. Um dia de tempo livre na praia definida pelo organizador, com transporte de ida e volta. O ponto exato do passeio será informado na confirmação; fotos apresentam referências visuais da região.'},
 {id:'ilhabela',name:'Ilhabela',category:'Ilhas & natureza',state:'SP',origins:['sp','sjc'],boarding:['São Paulo · Tietê · 04h','São José dos Campos · Centro · 05h30'],subtitle:'Uma ilha para trocar o relógio pelo som do mar.',description:'Roteiro fictício para descobrir Ilhabela, no litoral norte paulista. Inclui deslocamento terrestre e travessia de balsa neste exemplo. Tempo livre na orla; acesso a Castelhanos, Bonete e passeios de jipe ou barco não estão incluídos. A imagem é uma referência da região, não uma garantia de visita a uma praia específica.'},
 {id:'guarapari',name:'Guarapari',category:'Litoral do ES',state:'ES',origins:['vitoria','vila-velha'],boarding:['Vitória · Centro · 07h','Vila Velha · Centro · 07h30'],subtitle:'Entre enseadas, areia e a brisa do litoral capixaba.',description:'Uma saída demonstrativa para o litoral de Guarapari, no Espírito Santo. O roteiro prevê transporte de ida e volta e tempo livre na praia indicada pelo organizador. Fotografias da Enseada Azul são referências visuais; o local do passeio deve ser confirmado antes de uma reserva real.'}
];
const coastDates=[['arraial','2026-10-18',189,38],['ilha-grande','2026-10-25',249,31],['ubatuba','2026-11-01',179,27],['ilhabela','2026-11-08',229,34],['guarapari','2026-11-15',119,22],['arraial','2026-11-21',199,28],['ubatuba','2026-11-22',189,19],['ilha-grande','2026-12-05',259,33],['guarapari','2026-12-06',129,25]];
trips.splice(0,trips.length,...coastDates.map(([baseId,date,price,confirmed],i)=>{const base=coastBases.find(t=>t.id===baseId),d=new Date(date+'T12:00:00');return {...base,id:i<5?baseId:baseId+'-'+date,image:coastImages[baseId],galleryDestination:baseId,date,price,confirmed,capacity:46,dateLabel:d.toLocaleDateString('pt-BR',{day:'2-digit',month:'short',weekday:'short'}),fullDate:d.toLocaleDateString('pt-BR',{day:'numeric',month:'long',year:'numeric'}),time:({guarapari:'07:00',ubatuba:'04:30',ilhabela:'04:00'})[baseId]||'05:00',returnTime:baseId==='guarapari'?'19:00':'22:00',included:['Transporte de ida e volta','Orientações de embarque e retorno',...(baseId==='ilha-grande'?['Travessia até a Vila do Abraão']:baseId==='ilhabela'?['Travessia de balsa']:['Tempo livre no destino'])],excluded:['Alimentação e bebidas','Passeios opcionais e despesas pessoais'],schedule:[['Embarque','Encontro e saída','Confira o horário de cada ponto de embarque.'],['Manhã','Chegada ao litoral','Orientações do organizador e início do tempo livre.'],['Tarde','Praia no seu ritmo','Almoço livre e tempo para aproveitar a paisagem.'],['Retorno','Encontro do grupo','Horário final informado pelo organizador. Roteiro demonstrativo.']]}}));
filter={category:'Todos',query:'',month:'all',origin:'all'};
for(const base of coastBases)destinationPhotos[base.id]=[[coastImages[base.id],`${base.name} · referência visual da região`]];

destinationPhotos.ubatuba.push(['https://turismo.ubatuba.sp.gov.br/wp-content/uploads/sites/29/2014/11/DSC04690.jpg','Litoral de Ubatuba · imagem de referência']);
const coastPast=renderPastTrip;renderPastTrip=function(){return coastPast().replaceAll('assets/cipo.jpg',coastImages.arraial).replaceAll('Um dia na Serra do Cipó','Um dia em Arraial do Cabo').replaceAll('Cachoeira na Serra do Cipó','Litoral de Arraial do Cabo').replaceAll('Paisagem de cachoeira do álbum demonstrativo','Praia do álbum demonstrativo').replaceAll('https://images.unsplash.com/photo-1551632811-561732d1e306?w=800&auto=format&fit=crop',coastImages['ilha-grande']).replaceAll('Pessoas caminhando em uma trilha, foto ilustrativa do álbum','Paisagem litorânea, foto ilustrativa do álbum')};
