// Local client edition. The published GitHub demo is intentionally unchanged.
let excursionPeople=1;
const excursionDestinations=()=>trips.filter((t,i,a)=>a.findIndex(x=>x.name===t.name)===i);
function excursionContact(){
 bookingDialog.innerHTML=`<div class="dialog-header"><div><span>Vamos conversar</span><h2 id="booking-title">Qual é a sua próxima excursão?</h2></div>${closeButton()}</div><p class="contact-intro">Conte o que você procura. Esta demonstração simula o atendimento, sem enviar seus dados.</p><form id="excursion-contact-form"><div class="form-grid"><label>Seu nome<input class="control" name="name" required minlength="3" maxlength="80" placeholder="Nome fictício para testar"></label><label>Destino de interesse<select class="control" name="trip"><option value="">Ainda estou escolhendo</option>${excursionDestinations().map(t=>`<option>${esc(t.name)}</option>`).join('')}</select></label><label>Sua dúvida<textarea class="control" name="message" rows="3" maxlength="800" required placeholder="Quero saber sobre o embarque, as vagas..."></textarea></label></div><p class="fine-print">O WhatsApp do organizador será conectado quando a operação tiver um número definido.</p><div class="form-actions"><button type="button" data-close class="button secondary">Voltar</button><button class="button" type="submit">Simular atendimento</button></div></form>`;
 bookingDialog.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>bookingDialog.close());bookingDialog.querySelector('form').onsubmit=e=>{e.preventDefault();bookingDialog.close();toast('Atendimento simulado. Nenhum dado ou mensagem foi enviado.')};bookingDialog.showModal();
}
function excursionPhoto(id){const t=trips.find(t=>t.id===id);bookingDialog.innerHTML=`<div class="dialog-header"><div><span>Álbum de destinos · fotos ilustrativas</span><h2 id="booking-title">${esc(t.name)}</h2></div>${closeButton()}</div><img class="excursion-enlarged" src="${t.image}" alt="Paisagem de ${esc(t.name)}"><a class="button full" href="#viagem/${t.id}" data-close>Conhecer esta excursão</a>`;bookingDialog.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>bookingDialog.close());bookingDialog.showModal()}
function excursionScroll(id){if(!document.getElementById(id)){location.hash='viagens';requestAnimationFrame(()=>document.getElementById(id)?.scrollIntoView({behavior:'smooth'}))}else document.getElementById(id).scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})}
const originalExcursionHome=renderHome;
renderHome=function(){
 originalExcursionHome();document.title='JP Excursões — sua próxima excursão';
 const root=app.querySelector('.container'),hero=app.querySelector('.hero'),copy=hero.querySelector('.hero-copy');
 copy.innerHTML=`<span class="eyebrow">${icon('pin')}Praias e paraísos do Sudeste</span><h1>Menos rotina.<br>Mais dias<br><em>de mar.</em></h1><p>Água azul, areia e novos horizontes. Descubra praias e ilhas de São Paulo, Rio de Janeiro e Espírito Santo.</p><div class="excursion-hero-actions"><button class="button" data-section="destinos">Ver próximas excursões ${icon('back')}</button><button class="excursion-outline" data-contact>${icon('users')}Conversar com a equipe</button></div><span class="excursion-hero-note"><i></i>Saídas em São Paulo, Rio de Janeiro e Espírito Santo</span>`;
 hero.querySelector('.photo-caption').remove();hero.querySelector('.hero-chip').remove();
 hero.insertAdjacentHTML('beforeend','<div class="excursion-route-art" aria-hidden="true"><span>01 / SEU PRÓXIMO PARAÍSO</span><svg viewBox="0 0 440 160" fill="none"><path d="M10 140C80 145 100 12 185 28S245 160 345 90 395 25 420 20" stroke="currentColor" stroke-width="2" stroke-dasharray="5 8"/><circle cx="420" cy="20" r="12" fill="currentColor"/></svg></div>');
 hero.querySelector('.hero-search-heading').innerHTML='<span>Para onde vamos?</span><small>Encontre uma excursão do seu jeito.</small>';
 const form=document.getElementById('search-form');hero.querySelector('.hero-video').poster=coastImages.arraial;hero.querySelector('.hero-video source').src=coastVideo;hero.querySelector('.hero-video').load();hero.querySelector('.hero-photo').href='#viagem/arraial';hero.querySelector('.hero-photo').style.backgroundImage='url("'+coastImages.arraial+'")';hero.querySelector('.hero-photo').style.backgroundSize='cover';
 form.querySelector('[for="origin"]').textContent='Local de embarque';form.querySelector('[for="month"]').textContent='Data da excursão';form.querySelector('button[type="submit"]').innerHTML=icon('search')+'Buscar excursões';
 const passenger=document.createElement('div');passenger.className='search-field';passenger.innerHTML=`<label for="excursion-people">Passageiros</label><select id="excursion-people">${[1,2,3,4,5,6].map(n=>`<option value="${n}" ${n===excursionPeople?'selected':''}>${n} ${n===1?'pessoa':'pessoas'}</option>`).join('')}</select>`;form.insertBefore(passenger,form.querySelector('button[type="submit"]'));passenger.querySelector('select').onchange=e=>excursionPeople=Number(e.target.value);
 form.addEventListener('submit',()=>excursionScroll('destinos'));
 const filters=app.querySelector('.filter-row');filters.innerHTML=['Todos','Litoral do RJ','Litoral de SP','Litoral do ES','Ilhas & natureza'].map(c=>`<button class="filter ${filter.category===c?'active':''}" data-category="${esc(c)}" type="button" aria-pressed="${filter.category===c}">${esc(c)}</button>`).join('');filters.querySelectorAll('[data-category]').forEach(b=>b.onclick=()=>{filter.category=b.dataset.category;filters.querySelectorAll('button').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b))});updateCards();excursionScroll('destinos')});hero.querySelector('.hero-search').prepend(filters);
 const section=app.querySelector('#destinos');section.querySelector('h2').textContent='Escolha sua próxima excursão';section.querySelector('.section-title p').textContent='Seu próximo dia de sol começa com um destino.';section.querySelector('.all-trips-link').textContent='Ver mais viagens';section.querySelector('.all-trips-link').classList.add('button');section.querySelector('.nature-story').remove();section.querySelector('.help-strip').remove();
 section.insertAdjacentHTML('beforebegin',`<section class="excursion-benefits" aria-label="Do primeiro clique ao retorno">${[['pin','Embarque perto de você','Consulte as cidades e os pontos de saída.'],['bus','Ida e volta organizada','Veja horários e transporte de cada roteiro.'],['users','Atendimento próximo','Tire suas dúvidas antes de reservar.'],['ticket','Tudo às claras','Confira valores, vagas e o que está incluso.']].map(([i,h,p])=>`<div>${icon(i)}<h3>${h}</h3><p>${p}</p></div>`).join('')}</section>`);
 root.insertAdjacentHTML('beforeend',`
 <section class="excursion-section" id="lugares"><div class="excursion-heading"><span class="eyebrow">O melhor do litoral do Sudeste</span><h2>Qual paraíso combina com você?</h2><p>Enseadas, ilhas e praias que dão vontade de ficar.</p></div><div class="excursion-destination-grid">${excursionDestinations().map(t=>`<a href="#viagem/${t.id}" class="excursion-destination"><img src="${t.image}" alt="Paisagem de ${esc(t.name)}" loading="lazy"><div><span>${esc(t.category)}</span><h3>${esc(t.name)}</h3><small>${trips.filter(x=>x.name===t.name).length} ${trips.filter(x=>x.name===t.name).length===1?'saída disponível':'saídas disponíveis'} ↗</small></div></a>`).join('')}</div></section>
 <section class="excursion-transport excursion-section" id="transporte"><div><span class="eyebrow">Do embarque ao retorno</span><h2>A experiência começa<br>antes do destino.</h2><p>Um bom passeio também depende de saber como chegar. Cada excursão reúne as informações para você planejar sua ida e aproveitar o dia.</p><div class="excursion-transport-features">${[['pin','Pontos de embarque','Escolha sua cidade e o ponto de saída.'],['clock','Horários do roteiro','Confira a programação e o retorno.'],['bus','Transporte informado','Veja o que faz parte da excursão.'],['users','Orientação do organizador','Alinhe os detalhes antes de embarcar.']].map(([i,h,p])=>`<div>${icon(i)}<span><h3>${h}</h3><p>${p}</p></span></div>`).join('')}</div><button class="button" data-section="destinos">Encontrar uma excursão ↗</button></div><div class="excursion-transport-photo"><img src="${coastImages['ilha-grande']}" alt="Litoral e Mata Atlântica na região de Angra dos Reis" loading="lazy"><span>${icon('bus')}O caminho também faz parte da história.</span></div></section>
 <section class="excursion-how excursion-section" id="como-reservar"><div class="excursion-heading"><span class="eyebrow">Sem complicar</span><h2>Do destino escolhido à mala pronta.</h2><p>Conheça o passo a passo da sua próxima excursão.</p></div><div class="excursion-steps">${[['Escolha seu destino','Explore as datas, os roteiros e as vagas disponíveis.'],['Conte quem vai','Selecione os passageiros e o ponto de embarque.'],['Confira sua reserva','Revise os dados e as condições da excursão.'],['Prepare-se para sair','Combine a confirmação e as orientações com o organizador.']].map(([h,p],i)=>`<div><span>0${i+1}</span><h3>${h}</h3><p>${p}</p></div>`).join('')}</div><p class="fine-print">Nesta amostra, reservas e pagamentos são apenas demonstrativos.</p></section>
 <section class="excursion-about excursion-section" id="sobre-bora"><img src="${coastImages.guarapari}" alt="Enseada Azul em Guarapari" loading="lazy"><div><span class="eyebrow">Prazer, somos a JP Excursões.</span><h2>Pés na areia.<br>Histórias para levar.</h2><p>A JP Excursões nasceu da vontade de trocar a correria por dias de sol e boas companhias. Organizamos saídas para praias e ilhas do Sudeste, com atenção aos detalhes e um jeito próximo de receber cada viajante. Da primeira conversa ao retorno, nossa equipe acompanha sua próxima história à beira-mar.</p><div class="excursion-about-tags"><span>${icon('leaf')}Natureza</span><span>${icon('sun')}Praias</span><span>${icon('users')}Boas companhias</span></div><button class="story-link" data-contact>Conheça nossa equipe ↗</button></div></section>
 <section class="excursion-section" id="memorias"><div class="excursion-heading"><span class="eyebrow">Um gostinho do que vem por aí</span><h2>Lugares que merecem um lugar no seu álbum.</h2><p>Fotos ilustrativas dos destinos da nossa demonstração.</p></div><div class="excursion-mosaic">${excursionDestinations().map(t=>`<button class="excursion-memory" data-photo="${t.id}" aria-label="Ampliar foto de ${esc(t.name)}"><img src="${t.image}" alt="${esc(t.name)}" loading="lazy"><span>${esc(t.name)}<b>↗</b></span></button>`).join('')}</div></section>
 <section class="excursion-reviews excursion-section"><div class="excursion-heading"><span class="eyebrow">Experiências compartilhadas</span><h2>A viagem continua nas histórias.</h2><p>Exemplos de avaliações para apresentar a plataforma. Não são relatos reais.</p></div><div class="excursion-review-grid">${[['Marina C.','Arraial do Cabo','Gostei de conseguir ver os horários e o ponto de saída antes de reservar.'],['Lucas A.','Ubatuba','O roteiro ajudou a planejar o dia e saber o que estava incluso.'],['Camila S.','Guarapari','Foi fácil consultar as vagas e escolher uma saída para o grupo.']].map(([n,t,q])=>`<article><span class="excursion-stars" aria-label="5 estrelas ilustrativas">★★★★★</span><blockquote>“${q}”</blockquote><div><span class="excursion-avatar">${n[0]}</span><span><b>${n}</b><small>${t} · exemplo fictício</small></span></div></article>`).join('')}</div></section>
 <section class="excursion-questions excursion-section" id="duvidas"><div class="excursion-heading"><span class="eyebrow">Antes de embarcar</span><h2>Vamos tirar suas dúvidas?</h2></div>${[['Como escolho o ponto de embarque?','Abra a excursão e consulte o seletor de embarque. Cada saída apresenta seus próprios pontos e horários.'],['Posso reservar para um grupo?','Sim. Você pode simular uma reserva para até seis passageiros, respeitando as vagas disponíveis.'],['O que está incluso no valor?','Cada página apresenta transporte, acompanhamento e demais itens previstos, além das despesas por conta do passageiro.'],['Como funciona o pagamento e o cancelamento?','Esta amostra não cobra pagamentos. Em uma operação real, o organizador deve apresentar as condições de confirmação e cancelamento antes da compra.']].map(([q,a])=>`<details class="faq-item"><summary>${q}</summary><p>${a}</p></details>`).join('')}</section>
 <section class="excursion-last-call excursion-section"><span class="eyebrow">O próximo caminho chama</span><h2>O mar está chamando.<br>Vamos nessa?</h2><p>Escolha seu destino e convide quem vai viver isso com você.</p><div><button class="button" data-section="destinos">Ver próximas excursões ↗</button><button class="excursion-outline" data-contact>Conversar com a equipe</button></div></section>
 `);
 app.querySelectorAll('[data-section]').forEach(b=>b.onclick=()=>excursionScroll(b.dataset.section));app.querySelectorAll('[data-contact]').forEach(b=>b.onclick=excursionContact);app.querySelectorAll('[data-photo]').forEach(b=>b.onclick=()=>excursionPhoto(b.dataset.photo));
};
const originalExcursionAll=renderAllTrips;renderAllTrips=function(){originalExcursionAll();app.querySelectorAll('.excursion-section,.excursion-benefits').forEach(e=>e.remove());const title=app.querySelector('.catalog-heading h1');title.textContent='Todas as excursões';app.querySelector('.catalog-heading p').textContent='9 saídas demonstrativas para conhecer praias e ilhas do litoral de RJ, SP e ES.';app.querySelector('.section-title h2').textContent='Escolha sua próxima excursão';document.title='Todas as excursões · JP Excursões'};
const originalExcursionDetail=renderDetail;renderDetail=function(id){originalExcursionDetail(id);const people=document.getElementById('people');if(people){people.value=String(Math.min(excursionPeople,people.options.length));people.dispatchEvent(new Event('change'))}};
document.querySelector('.header-inner>nav').innerHTML='<a href="#viagens" data-nav="viagens">Início</a><button data-global-section="lugares">Destinos</button><button data-global-section="como-reservar">Como reservar</button><button data-global-section="sobre-bora">Sobre</button>';
document.querySelector('.header-inner').insertAdjacentHTML('beforeend','<button class="excursion-header-contact" data-global-contact>Fale com a gente ↗</button>');
document.querySelector('.site-footer').innerHTML=`<div class="excursion-footer-grid"><div><a class="logo" href="#viagens"><span class="brand-symbol">JP</span><span class="jp-brand-name">Excursões</span></a><p>Da vontade de ver o mar à próxima saída.<br>Praias e ilhas do Sudeste.</p></div><div><h3>Explore</h3><button data-global-section="lugares">Destinos em destaque</button><button data-global-section="como-reservar">Como reservar</button></div><div><h3>Embarques</h3><p>São Paulo · São José dos Campos<br>Rio de Janeiro · Niterói<br>Vitória · Vila Velha</p><small>Consulte os pontos de cada excursão.</small></div><div><h3>Vamos conversar?</h3><p>Dúvidas sobre a próxima saída?<br>Estamos por aqui.</p><button class="excursion-footer-contact" data-global-contact>Conversar com a equipe ↗</button></div></div><div class="excursion-footer-bottom"><span>JP Excursões · demonstração de plataforma de excursões</span><span>Empresa e textos fictícios · sem compras ou cobranças reais</span></div>`;
document.querySelectorAll('[data-global-section]').forEach(b=>b.onclick=()=>excursionScroll(b.dataset.globalSection));document.querySelectorAll('[data-global-contact]').forEach(b=>b.onclick=excursionContact);
document.body.insertAdjacentHTML('beforeend','<button class="excursion-floating-contact" aria-label="Conversar com a equipe">'+icon('users')+'</button>');document.querySelector('.excursion-floating-contact').onclick=excursionContact;
renderRoute(false);
