const destinationPhotos={
 cipo:[['https://cdn.checkinweb.com.br/img/22/upload/images/serracipo_cachoeiras/cachoeira_grande.png','Cachoeira Grande, Serra do Cipó'],['https://cdn.checkinweb.com.br/img/22/upload/images/serracipo_cachoeiras/cachoeira_veu_da_noiva.png','Cachoeira Véu da Noiva, Serra do Cipó']],
 'ouro-preto':[['https://experience-travel.b-cdn.net/activiteiten/brazili%C3%AB/bezoek-unesco-werelderfgoed-ouro-preto-mariana/hero/street-in-ouro-preto-city.jpg?aspect_ratio=2%3A1&width=1224&height=612&format=jpeg','Ruas e arquitetura de Ouro Preto']],
 inhotim:[['https://thesummerhunter.com/midia/assets/1662d14e-437e-5e8a-8eac-fb022b81f8cb/inhotim-botanico-giovanni-bello-2.jpg?format=avif','Jardins de Inhotim']]
};
function renderGallery(t){const photos=[[t.image,`Paisagem de ${t.name}`],...(destinationPhotos[t.galleryDestination||t.id]||[])];return `<section class="travel-gallery" aria-label="Galeria de ${esc(t.name)}"><button class="gallery-main" type="button" aria-label="Ampliar foto da viagem"><img class="detail-cover" src="${esc(photos[0][0])}" alt="${esc(photos[0][1])}"><span class="gallery-expand">${icon('grid')}Ver fotos <span class="gallery-count">1 / ${photos.length}</span></span></button><div class="gallery-thumbs">${photos.map(([src,alt],i)=>`<button type="button" class="gallery-thumb ${i===0?'active':''}" aria-label="Ver foto ${i+1}: ${esc(alt)}" aria-pressed="${i===0}" data-photo="${i}"><img src="${esc(src)}" alt="${esc(alt)}" loading="lazy"></button>`).join('')}<p>Fotos do destino<br><span>Referências visuais da região</span></p></div></section>`}
function bindGallery(){const gallery=document.querySelector('.travel-gallery');if(!gallery)return;const thumbs=[...gallery.querySelectorAll('.gallery-thumb')];const photos=thumbs.map(b=>({src:b.querySelector('img').src,alt:b.querySelector('img').alt}));let current=0;const main=gallery.querySelector('.gallery-main img');const dialog=document.createElement('dialog');dialog.className='gallery-lightbox';dialog.setAttribute('aria-label','Fotos da viagem');dialog.innerHTML='<button type="button" class="gallery-close" aria-label="Fechar galeria">×</button><button type="button" class="gallery-prev" aria-label="Foto anterior">←</button><figure><img alt=""><figcaption></figcaption></figure><button type="button" class="gallery-next" aria-label="Próxima foto">→</button>';document.querySelector('.gallery-lightbox')?.remove();document.body.append(dialog);
 function show(i){current=(i+photos.length)%photos.length;main.src=photos[current].src;main.alt=photos[current].alt;thumbs.forEach((b,j)=>{b.classList.toggle('active',j===current);b.setAttribute('aria-pressed',String(j===current))});gallery.querySelector('.gallery-count').textContent=`${current+1} / ${photos.length}`;const img=dialog.querySelector('img');img.src=photos[current].src;img.alt=photos[current].alt;dialog.querySelector('figcaption').textContent=`${photos[current].alt} · ${current+1} / ${photos.length}`}
 thumbs.forEach((b,i)=>b.addEventListener('click',()=>show(i)));gallery.querySelector('.gallery-main').onclick=()=>{show(current);dialog.showModal()};dialog.querySelector('.gallery-close').onclick=()=>dialog.close();dialog.querySelector('.gallery-prev').onclick=()=>show(current-1);dialog.querySelector('.gallery-next').onclick=()=>show(current+1);dialog.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'){e.preventDefault();show(current-1)}if(e.key==='ArrowRight'){e.preventDefault();show(current+1)}});dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});let start=0;dialog.querySelector('img').addEventListener('touchstart',e=>{start=e.changedTouches[0].clientX},{passive:true});dialog.querySelector('img').addEventListener('touchend',e=>{const dx=e.changedTouches[0].clientX-start;if(Math.abs(dx)>50)show(current+(dx<0?1:-1))},{passive:true});
}
